/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Mon Feb 20 2017 14:45:24 GMT-0300 (Hora oficial do Brasil)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
import { AppEnv } from './env.model';
export declare const ENV: AppEnv;
